name: Build vpp prod image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: initialize environment
      run: |
        sudo mkdir -p /work/release
        sudo chown -R $USER:$GROUPS /work
        
    - name: Get code
      run: |
        git clone https://github.com/FDio/vpp.git
        ln -sf $GITHUB_WORKSPACE/vpp /work/vpp
        git clone https://github.com/liudf0716/vpp-agent.git
        ln -sf $GITHUB_WORKSPACE/vpp-agent/docker/prod /work/vpp-agent
        
    - name: Build dpdk depend
      run: |
        cd vpp
        git checkout stable/2009
        make install-dep UNATTENDED=y
        make install-ext-dep
        cp build/external/*.deb /work/vpp-agent/
        
    - name: Build vpp-agent
      run: |
        cd vpp-agent
        make cmd
        cp cmd/agentctl/agentctl /work/vpp-agent/
        cp cmd/vpp-agent/vpp-agent /work/vpp-agent/
        cp cmd/vpp-agent-init/vpp-agent-init /work/vpp-agent/
    
    - name: Pull vpp-base
      run: |
        sudo docker pull  ligato/vpp-base:20.09
    
    - name: Build prod image
      run: |
        ls /work/release/
        cd vpp-agent
        make prod-image
        docker images
        
    - name: update image
      run: |
        docker tag prod_vpp_agent:latest liudf0716/vpp-wrt:20.09
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push liudf0716/vpp-wrt:20.09
      
    - name: Setup debug session
      uses: csexton/debugger-action@master
