name: Build vpp prod image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: initialize environment
      run: |
        sudo mkdir -p /work/release
        sudo chown -R $USER:$GROUPS /work
        
    - name: Get code
      run: |
        git clone https://github.com/FDio/vpp.git
        ln -sf /work/vpp $GITHUB_WORKSPACE/vpp
        git clone https://github.com/liudf0716/vpp-agent.git
        ln -sf /work/vpp-agent $GITHUB_WORKSPACE/vpp-agent
        
    - name: Build vpp
      run: |
        cd vpp
        git checkout stable/2009
        make install-dep UNATTENDED=y
        # make install-ext-dep
        # make pkg-deb
        # cp build-root/*.deb /work/release
        # rm -f /work/release/vpp-dbg*.deb
        # cp build/external/*.deb /work/release
        
    - name: Build vpp-agent
      run: |
        cd vpp-agent
        make cmd
        cp cmd/agentctl/agentctl /work/release/
        cp cmd/vpp-agent/vpp-agent /work/release/
        cp cmd/vpp-agent-init/vpp-agent-init /work/release/
        
    - name: upload release file 
      uses: liudf0716/upload-artifact@v2.2.2
      with:
         name: vpp_release
         path: /work/release
    
    - name: setup debug session
      uses: csexton/debugger-action@master
    
    - name: Build prod image
      run: |
        ls /work/release/
        cd vpp-agent
        make prod-image
        docker image

